### ISSUE TITLE
Possible missing dependencies

### ISSUE THREAD

**Issue by AnotherOneAckap** [houseabsolute/DateTime-Format-Strptime#23]
Hello, thank you for your job, it really comes handy.
So here is my problem: when I'm trying to install it through cpanm, installation didn't finish succesful until I install Class::Singleton manually. 
I wonder is it really a bug, or just my bad?
Thanks in advance.

**Comment by autarch** [comment]
That's not a direct dependency of DT::F::Strptime, but it's a transitive one via DateTime::TimeZone. That said, DT::TZ does declare this as a dep. I've never heard of anyone else having this issue, so I'm not sure what happened in your case.
