### ISSUE TITLE
Broken support for DateTime::TimeZone::Tzfile

### ISSUE THREAD

**Issue by choroba** [houseabsolute/DateTime-Format-Strptime#30]
Since a01f3ff133bc822e847bc83c78faaea15db0ee18, we cannot use
[DateTime::TimeZone::Tzfile](http://p3rl.org/DateTime::TimeZone::Tzfile) because

>The DateTime::TimeZone::Tzfile class is not a subclass of the DateTime::TimeZone class

Could it be added as a supported class?

Another option would be to change DT:TZ:T to be a descendant of DT:TZ, but last change there was in 2017 :-(

**Comment by autarch** [comment]
Thanks for the report. This is fixed in v1.79.
