### ISSUE TITLE
Unable to parse legitimate pattern [on Win32 x64]

### ISSUE THREAD

**Issue by CmdrStukov** [houseabsolute/DateTime-Format-Strptime#32]
Hi,

I am trying to parse a date pattern and it fails unexpectedly:

This works:
>perl -MDateTime::Format::Strptime -wle"print DateTime::Format::Strptime->new(pattern => '%a, %d %b %Y %T %z',locale => 'en_GB',time_zone => 'Europe/London', on_error  => 'croak')->parse_datetime('Tue, 31 Aug 2021 13:29:36 +0100');"

This does not work:
>perl -MDateTime::Format::Strptime -wle"print DateTime::Format::Strptime->new(pattern => '%a, %d %b %Y %T %z',locale => 'en_GB',time_zone => 'Europe/London', on_error  => 'croak')->parse_datetime('Wed,  1 Sep 2021 01:45:51 +0100');"

It fails trying to parse the date string: `Wed,  1 Sep 2021 01:45:51 +0100` on Win32 x64 running perl v5.34.
Any ideas?

Kind regards,
CmdrStukov

**Comment by autarch** [comment]
This works for me. Can you include the actual error that you get?

**Comment by CmdrStukov** [comment]
For posterity:

>C:\Work\Programming\perl>perl -MDateTime::Format::Strptime -wle"print DateTime::Format::Strptime->new(pattern => '%a, %d %b %Y %T %z',locale => 'en_GB',time_zone => 'Europe/London', on_error => 'croak')->parse_datetime('Wed, 1 Sep 2021 01:45:51 +0100');"
>Your datetime does not match your pattern. at -e line 1.
>
>C:\Work\Programming\perl>perl -MDateTime::Format::Strptime -wle"print DateTime::Format::Strptime->new(pattern => '%a, %d %b %Y %T %z',locale => 'en_GB',time_zone => 'Europe/London', on_error => 'croak')->parse_datetime('Wed, 1 Sept 2021 01:45:51 +0100');"
>2021-09-01T01:45:51
>
>C:\Work\Programming\perl>
>C:\Work\Programming\perl>perl -v
>  This is perl 5, version 34, subversion 0 (v5.34.0) built for MSWin32-x64-multi-thread
>  Copyright 1987-2021, Larry Wall
>  Perl may be copied only under the terms of either the Artistic License or the
>GNU General Public License, which may be found in the Perl 5 source kit.
>  Complete documentation for Perl, including FAQ lists, should be found on
>this system using "man perl" or "perldoc perl".  If you have access to the
>Internet, point your browser at http://www.perl.org/, the Perl Home Page.
>    C:\Work\Programming\perl>perl -V
>Summary of my perl5 (revision 5 version 34 subversion 0) configuration:
>    Platform:
>    osname=MSWin32
>    osvers=10.0.14393
>    archname=MSWin32-x64-multi-thread
>    uname=''
>    config_args='undef'
>    hint=recommended
>    useposix=true
>    d_sigaction=undef
>    useithreads=define
>    usemultiplicity=define
>    use64bitint=define
>    use64bitall=undef
>    uselongdouble=undef
>    usemymalloc=n
>    default_inc_excludes_dot=define
>  Compiler:
>    cc='cl'
>    ccflags ='-nologo -GF -W3 -MD -DWIN32 -D_CONSOLE -DNO_STRICT -DWIN64 -D_CRT_SECURE_NO_DEPRECATE -D_CRT_NONSTDC_NO_DEPRECATE -D_WINSOCK_DEPRECATED_NO_WARNINGS  -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS'
>    optimize='-O1 -Zi -GL -fp:precise'
>    cppflags='-DWIN32'
>    ccversion='19.29.30038.1'
>    gccversion=''
>    gccosandvers=''
>    intsize=4
>    longsize=4
>    ptrsize=8
>    doublesize=8
>    byteorder=12345678
>    doublekind=3
>    d_longlong=undef
>    longlongsize=8
>    d_longdbl=define
>    longdblsize=8
>    longdblkind=0
>    ivtype='__int64'
>    ivsize=8
>    nvtype='double'
>    nvsize=8
>    Off_t='__int64'
>    lseeksize=8
>    alignbytes=8
>    prototype=define
>  Linker and Libraries:
>    ld='link'
>    ldflags ='-nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"c:\perl-5.34.0\lib\CORE"  -machine:AMD64 -subsystem:console,"5.02"'
>    libpth="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\\lib\x64"
>    libs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib vcruntime.lib ucrt.lib
>    perllibs=oldnames.lib kernel32.lib user32.lib gdi32.lib winspool.lib  comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib  netapi32.lib uuid.lib ws2_32.lib mpr.lib winmm.lib  version.lib odbc32.lib odbccp32.lib comctl32.lib msvcrt.lib vcruntime.lib ucrt.lib
>    libc=ucrt.lib
>    so=dll
>    useshrplib=true
>    libperl=perl534.lib
>    gnulibc_version=''
>  Dynamic Linking:
>    dlsrc=dl_win32.xs
>    dlext=dll
>    d_dlsymun=undef
>    ccdlflags=' '
>    cccdlflags=' '
>    lddlflags='-dll -nologo -nodefaultlib -debug -opt:ref,icf -ltcg  -libpath:"c:\perl-5.34.0\lib\CORE"  -machine:AMD64 -subsystem:console,"5.02"'
>    Characteristics of this binary (from libperl):
>  Compile-time options:
>    HAS_TIMES
>    HAVE_INTERP_INTERN
>    MULTIPLICITY
>    PERLIO_LAYERS
>    PERL_COPY_ON_WRITE
>    PERL_DONT_CREATE_GVSV
>    PERL_IMPLICIT_CONTEXT
>    PERL_IMPLICIT_SYS
>    PERL_MALLOC_WRAP
>    PERL_OP_PARENT
>    PERL_PRESERVE_IVUV
>    USE_64_BIT_INT
>    USE_ITHREADS
>    USE_LARGE_FILES
>    USE_LOCALE
>    USE_LOCALE_COLLATE
>    USE_LOCALE_CTYPE
>    USE_LOCALE_NUMERIC
>    USE_LOCALE_TIME
>    USE_PERLIO
>    USE_PERL_ATOF
>    USE_THREAD_SAFE_LOCALE
>  Built under MSWin32
>  Compiled at Jul  5 2021 17:36:31
>  %ENV:
>    PERL5LIB="C:\Work\Programming\perl\lib"
>    PERL_HOME="C:\perl-5.34.0"
>  @INC:
>    C:\Work\Programming\perl\lib
>    C:/perl-5.34.0/site/lib/MSWin32-x64-multi-thread
>    C:/perl-5.34.0/site/lib
>    C:/perl-5.34.0/lib

**Comment by autarch** [comment]
Ah, I think I see the issue. I tested first with an older version of `DateTime::Locale`. I get the same error as you when I use the latest. It looks like the abbreviation for September changed to "Sept" in some recent version of `DateTime::Locale`. This locale data comes from the [CLDR project](https://cldr.unicode.org/) and I'm not sure _why_ it changed. It's a bit odd since all the other abbreviated months are still 3 characters.

It looks like there are already a couple tickets filed in the CLDR issue tracker about this:
* https://unicode-org.atlassian.net/browse/CLDR-14412
* https://unicode-org.atlassian.net/browse/CLDR-14936

It looks like they don't plan to change it back, but they are discussing providing additional data for parsers to use in the CLDR format. Once that data exists, we could update `DateTime::Locale` to provide that data and then make `DateTime::Format::Strptime` use that data.

For now, I'm going to close this issue, since this isn't really a bug in `DateTime::Format::Strptime`.

**Comment by CmdrStukov** [comment]
No worries, a quick and dirty `s/ Sep / Sept /i` gets me out of a hole for now.
Thank you for looking into this issue.

Kind regards,
CmdStukov
