### ISSUE TITLE
Incomplete support for ISO 8601 Time offsets

### ISSUE THREAD

**Issue by autarch** [houseabsolute/DateTime-Format-Strptime#9]
Migrated from [rt.cpan.org #109657](https://rt.cpan.org/Ticket/Display.html?id=109657) (status was 'open')

Requestors:

Attachments:
* [dt_strptime.t](https://rt.cpan.org/Ticket/Attachment/1565025/835389/dt_strptime.t)

From arunbear@gmail.com on 2015-11-25 12:06:27:

Good day,

it would seem that the offsets

+hh:mm
+hh

are not supported by this module, but use of the "%z" pattern would require
or imply such support.

I'm attaching a test script that shows this problem.

See also
https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

Version of DateTime::Format::Strptime tested was: 1.61

kind regards,
Arun

**Comment by autarch** [comment]
From drolsky@cpan.org (@autarch) on 2015-12-19 20:01:42:

On Wed Nov 25 07:06:27 2015, arunbear@gmail.com wrote:
> Good day,
> 
> it would seem that the offsets
> 
> +hh:mm
> +hh
> 
> are not supported by this module, but use of the "%z" pattern would require
> or imply such support.
> 
> I'm attaching a test script that shows this problem.
> 
> See also
> https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC
> 
> Version of DateTime::Format::Strptime tested was: 1.61

On my system, running "man strftime" gives me this output:

           %z     The +hhmm or -hhmm numeric timezone (that is, the hour and minute offset from UTC). (SU)

So this module seems to be doing what at least my glibc's version of strftime does. Is this different on other systems?

This module is really not supposed to be anything like a full ISO8601 parser. There is one on CPAN - https://metacpan.org/release/DateTime-Format-ISO8601

**Comment by autarch** [comment]
From srezic@cpan.org (@eserte) on 2015-12-19 20:39:56:

On 2015-12-19 15:01:42, DROLSKY wrote:
> On Wed Nov 25 07:06:27 2015, arunbear@gmail.com wrote:
> > Good day,
> >
> > it would seem that the offsets
> >
> > +hh:mm
> > +hh
> >
> > are not supported by this module, but use of the "%z" pattern would
> > require
> > or imply such support.
> >
> > I'm attaching a test script that shows this problem.
> >
> > See also
> > https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC
> >
> > Version of DateTime::Format::Strptime tested was: 1.61
> 
> On my system, running "man strftime" gives me this output:
> 
> %z     The +hhmm or -hhmm numeric timezone (that is, the hour and
> minute offset from UTC). (SU)
> 
> So this module seems to be doing what at least my glibc's version of
> strftime does. Is this different on other systems?
> 
> This module is really not supposed to be anything like a full ISO8601
> parser. There is one on CPAN - https://metacpan.org/release/DateTime-
> Format-ISO8601

But man strptime (on debian systems) says:

%z     An RFC-822/ISO 8601 standard timezone specification.

Experiments show that +hh:mm and +hh are recognized by the C strptime.

On freebsd systems only the +hhmm format is parsed.

**Comment by autarch** [comment]
From drolsky@cpan.org (@autarch) on 2015-12-19 20:42:24:

On Sat Dec 19 15:39:56 2015, SREZIC wrote:
> On 2015-12-19 15:01:42, DROLSKY wrote:
> > On Wed Nov 25 07:06:27 2015, arunbear@gmail.com wrote:
> > > Good day,
> > >
> > > it would seem that the offsets
> > >
> > > +hh:mm
> > > +hh
> > >
> > > are not supported by this module, but use of the "%z" pattern would
> > > require
> > > or imply such support.
> > >
> > > I'm attaching a test script that shows this problem.
> > >
> > > See also
> > > https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC
> > >
> > > Version of DateTime::Format::Strptime tested was: 1.61
> > 
> > On my system, running "man strftime" gives me this output:
> > 
> > %z     The +hhmm or -hhmm numeric timezone (that is, the hour and
> > minute offset from UTC). (SU)
> > 
> > So this module seems to be doing what at least my glibc's version of
> > strftime does. Is this different on other systems?
> > 
> > This module is really not supposed to be anything like a full ISO8601
> > parser. There is one on CPAN - https://metacpan.org/release/DateTime-
> > Format-ISO8601
> 
> But man strptime (on debian systems) says:
> 
> %z     An RFC-822/ISO 8601 standard timezone specification.
> 
> Experiments show that +hh:mm and +hh are recognized by the C strptime.
> 
> On freebsd systems only the +hhmm format is parsed.

Ah, good point. I will fix this when I get a round tuit but patches are welcome.

**Comment by abraxxa** [comment]
I'd also need this format to parse dates from Internet Explorer which doesn't support +0000 but only +00:00 for the timezone.

**Comment by abraxxa** [comment]
The hardest part seems to find an unused pattern character, I've gone with %zc for now as I wasn't able to find an unused single character one.

**Comment by abraxxa** [comment]
Which fails the roundtrip test because DateTime::strftime needs to support the pattern too and interprets %zc as '%z followed by a literal c'.
My work so far is in my fork, please advise which pattern character to use (Time::Moment uses %P which is already taken) and if we need to add support to DateTime::strftime too.

**Comment by chansen** [comment]
I think it would be better to extend the `%z` conversion specifier to accept:

```
±HH
±HHMM
±HH:MM
Z
```
Glibc [strptime](https://www.gnu.org/software/libc/manual/html_node/Low_002dLevel-Time-String-Parsing.html) ([implementation](https://github.com/IIJ-NetBSD/netbsd-src/blob/939664b96c98049eaf607000a6b2c5510fc7d44e/lib/libc/time/strptime.c#L456)) and NetBSD [strptime](http://netbsd.gw.com/cgi-bin/man-cgi?strptime++NetBSD-current) ([implementation](https://github.com/IIJ-NetBSD/netbsd-src/blob/939664b96c98049eaf607000a6b2c5510fc7d44e/lib/libc/time/strptime.c#L456)) accepts the above representations for the `%z` conversion specifier.

**Comment by chansen** [comment]
I've pushed a branch named '[chansen/extend_z](https://github.com/houseabsolute/DateTime-Format-Strptime/tree/chansen/extend_z)' that extend the accepted representations in the `%z` conversion specifier.

**Comment by autarch** [comment]
Fixed in #13

**Comment by abraxxa** [comment]
Thank you!
